// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

package org.tensorflow.example;

public final class ExampleProtos {
  private ExampleProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_Example_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_Example_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_SequenceExample_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_SequenceExample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rexample.proto\022\ntensorflow\032\rfeature.pro" +
      "to\"1\n\007Example\022&\n\010features\030\001 \001(\0132\024.tensor" +
      "flow.Features\"i\n\017SequenceExample\022%\n\007cont" +
      "ext\030\001 \001(\0132\024.tensorflow.Features\022/\n\rfeatu" +
      "re_lists\030\002 \001(\0132\030.tensorflow.FeatureLists" +
      "B,\n\026org.tensorflow.exampleB\rExampleProto" +
      "sP\001\370\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.tensorflow.example.FeatureProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_Example_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_Example_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_Example_descriptor,
        new java.lang.String[] { "Features", });
    internal_static_tensorflow_SequenceExample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_SequenceExample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_SequenceExample_descriptor,
        new java.lang.String[] { "Context", "FeatureLists", });
    org.tensorflow.example.FeatureProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
